---

version: '3'
services:
  test:
    build: .
    depends_on:
      - hub
      - chrome
    volumes:
      - './TestResults:/tests/TestResults'      
    networks:
      - selenium-test 
    environment:
      - adminexamplepassword     

  chrome:
    image: selenium/node-chrome 
    volumes:
      - /dev/shm:/dev/shm    
    networks:
      - selenium-test    
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 4
      NODE_MAX_SESSION: 4  


  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium-test          
    environment:
      - GRID_CLEAN_UP_CYCLE=500  

networks:
  selenium-test:      
